# Site settings
title: "Najam Ul Saqib Resume"
description: "Full Stack Developer Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Najam Ul Saqib"
resume_title: "Senior Full Stack Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "njmulsqb@protonmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+92-308-8438733"
resume_contact_address: "Gujranwala, Pakistan"

resume_header_contact_info: "Gujranwala, Pakistan • +92-308-8438733 • njmulsqb@protonmail.com"
display_header_contact_info: "false"

resume_header_intro: "<p>I am an experienced full stack developer who has worked across multiple stacks and technologies. My area of expertise lies in building scalable and secure apps using Javascript & Typescript frameworks. Here are the technologies I work in: ReactJS, ExpressJS, NextJS, NestJS, NodeJS, AWS, Azure, SQL. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/njmulsqb"
  #resume_twitter_url: "http://twitter.com/jglovier"
  #resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/njmulsqb"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url: "http://njmulsqb.github.io"
  #resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
